docs_dir: docs/book
site_dir: docs/html
extra:
    project: Components
    current_version: v2
    versions:
      - v2
      - v1
    installation:
        composer_dev: true
nav:
    - Home: index.md
    - v2:
        - 'Introduction': v2/intro.md
        - 'Coding Style Guide': v2/coding-style-guide.md
    - v1:
        - 'Introduction': v1/intro.md
        - 'Ruleset': v1/ruleset.md
site_name: laminas-coding-standard
site_description: 'The coding standard ruleset for Laminas components.'
repo_url: 'https://github.com/laminas/laminas-coding-standard'
